name: 05 - Simple Action

on:
  workflow_dispatch:

jobs:
  simple-action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - name: Send a Slack Message
        uses: ./.github/actions/slack-php
        with:
          slack_webhook: ${{ secrets.SLACK_WEBHOOK }}
          message: Hello Slack